language: node_js
node_js:
    - 0.8
    - 0.9
branches:
    only:
        - master
        - 3.x
        - dev-master
        - dev-3.x
before_install:
    - ./src/common/travis/before.sh
install:
    - ./src/common/travis/install.sh
script:
    - ./src/common/travis/test.sh
git:
    depth: 30
